server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/department_db
    username: root
    password: root
  application:
    name: DEPARTMENT-SERVICE
  zikpin:
    base-url: http://127.0.0.1:9411/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost